@startuml

skinparam monochrome true

note as N1
creation fields where
used to automatically
change all pair keys after
certain time
end note

object User {

}

object UserKey {
	name: char(200)
	publicKey: text
	privateKey: text
	creation: Date
}

note left
 We can have more than one key
 with differnt kinds of passphrase
 For example: Password & fingerprint
end note

object Group {
	name: char(200)
	publicKey: Text
	privateKey: Text
	keyCreation: Date
}

note bottom
public and private key
cypher with parent key
end note

object GroupUserPermission {
	permissions: Enum('read', 'write', 'admin')
}

note top
If there isn't association, means
the user haven't access to the group
end note

object GroupUserKey {
	publicKey: Text
	privateKey: Text
	keyCreation: Date
}
note bottom
public and private key, where cypher
with user key.

private key empty when user only have
read access
end note

object Site {
	name: Char(200)
	description: Text
	url: Char(200)
	user: Char(200)
	cypherType: Int
	password: Text
}

User "1" -- "*" UserKey
User "1" -- "*" GroupUserPermission
GroupUserPermission "*" -- "1" Group
Group "*" -- "1" Group : Parent
Group "1" -- "*" Site
GroupUserPermission "1" -- "*" GroupUserKey
UserKey "1" -- "*" GroupUserKey

@enduml
